# -*- coding: utf-8 -*-
"""guess_the_number

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D6m9dTo8SWRKXT1IczxGA7fcjU_tBIDO
"""

print("===== GUESS THE NUMBER! =====")

secret_number = 7
guess = 0

while guess != secret_number:
  print()
  guess = int(input("Guess the number: "))
  if guess == secret_number:
    print("Correct!")
    print("You win!")
  else:
    print("Wrong!")
    if guess < secret_number:
      print("Too low!")
    else:
      print("Too high!")