# -*- coding: utf-8 -*-
"""user_menu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tIQfsousd5HtfVkUv33OQaJSRtd4LRa1
"""

# Project : User Menu
# Day : 19
# Author  : Piyaphat Saengtho
# Language: Python
# Concepts:
# - Functions
# - Return
# - Parameters
# - if / elif / else
# - while loop
# - for loop
# - try / except
# - continue
# Description: A simple menu program that stores user information
# and demonstrates basic Python programming concepts.

def get_name():
  return input("Name: ")

def get_age():
  while True:
    try:
      return int(input("Age: "))
    except:
      print("Invalid age.")
      print()
      continue

name = get_name()
age = get_age()
print()


def line():
  return "=============================="

def header_name():
  return "         USER MENU         "

def show_menu():
   list_menu = ["Show Name", "Show Age", "Check Adult", "Exit"]
   count = 1
   for menu in list_menu:
    print(count, menu)
    count += 1

def show_name(name):
  return "Your name is " + name + "."

def show_age(age):
  return f"You are {age} years old."

def check_adult(age):
  if age >= 18:
    return "You are an adult."
  else:
    return "You are under 18."

def exit_message(name):
  return "Goodbye, " + name + "!"


choice = 0
while choice != 4:
  print(line())
  print(header_name())
  print(line())
  print()
  show_menu()
  print()
  try:
    choice = int(input("Choose: "))
  except:
    print("Invalid input. Please enter a number.")
    print()
    continue
  if choice == 1:
    print(show_name(name))
  elif choice == 2:
    print(show_age(age))
  elif choice == 3:
    print(check_adult(age))
  elif choice == 4:
    print(exit_message(name))
  print()