# -*- coding: utf-8 -*-
"""day14_functions_and_return

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwSbyaecCC7nBjRrtf_0oDVkzf1NFQDD
"""

# ========================================
# Topic: Functions, Parameter and return
# Day: 14
# Author: Pleng
# Description: Practice using functions,
# parameter and return values.
# ========================================

def full_name():
  first_name = input("Firs name: ")
  last_name = input("Last name: ")
  return first_name + " " + last_name
name = full_name()

def get_age():
  number = input("Age: ")
  return number
user_age = get_age()
print()

def welcome_message(name):
  return "Welcome, " + name + "!"

def goodbye_message(name):
  return "Have a nice day, " + name + "!"

def show_message(name, user_age):
  print(welcome_message(name))
  print()
  print("Age: " + user_age)
  print()
  print(goodbye_message(name))

show_message(name, user_age)